local wk = require("which-key")
wk.register({ t = { name = "toggle" } }, { prefix = "<leader>" })
wk.register({ p = { name = "picker" } }, { prefix = "<leader>" })
wk.register({ b = { name = "buffer" } }, { prefix = "<leader>" })
wk.register({ s = { name = "spectre" } }, { prefix = "<leader>s" })
-- wk.register({ f = { name = "file" } }, { prefix = "<leader>" })
wk.register({ l = { name = "lsp" } }, { prefix = "<leader>" })
wk.register({ s = { name = "search" } }, { prefix = "<leader>" })
-- wk.register({ e = { name = "misc" } }, { prefix = "<leader>" })
wk.register({ g = { name = "git" } }, { prefix = "<leader>" })
wk.register({ h = { name = "help" } }, { prefix = "<leader>" })
wk.register({ r = { name = "run" } }, { prefix = "<leader>" })

vim.keymap.set("n", "zR", require("ufo").openAllFolds)
vim.keymap.set("n", "zM", require("ufo").closeAllFolds)
vim.keymap.set("n", "<leader>td", "<cmd>SwitchTheme dark<CR>", { desc = "toggle random dark theme" })
vim.keymap.set("n", "<leader>tl", "<cmd>SwitchTheme light<CR>", { desc = "toggle random light theme" })
vim.keymap.set("n", "<leader>nd", "<cmd>NoiceDismiss<CR>", { desc = "dismiss noice" })
vim.keymap.set("n", "<leader>ts", "<cmd>InspectTree<CR>", { desc = "open treesitter tree" })
vim.keymap.set("n", "<A-j>", "yyp")
vim.keymap.set("n", "<A-k>", "yyP")
vim.keymap.set("i", "<A-j>", "<esc>yypI")
vim.keymap.set("i", "<A-k>", "<esc>yyPI")
vim.keymap.set("n", "<esc>", "<esc><cmd>noh<cr>")
vim.keymap.set("n", "<c-q>", "<cmd>q<CR>")
vim.keymap.set("n", "<leader>a", "ggVG", { desc = "select all content" })
vim.keymap.set("n", "<leader>q", vim.cmd.qa, { desc = "quit" })
vim.keymap.set("n", "<leader>w", vim.cmd.w, { desc = "write" })
vim.keymap.set("n", "<leader>hl", vim.cmd.Lazy, { desc = "open-lazy" })
vim.keymap.set("n", "<leader>.", ":so%<CR>")
-- vim.keymap.set("n", "<C-j>", "<c-w>j", { silent = true })
-- vim.keymap.set("n", "<C-k>", "<c-w>k", { silent = true })
-- vim.keymap.set("n", "<C-h>", "<c-w>h", { silent = true })
-- vim.keymap.set("n", "<C-l>", "<c-w>l", { silent = true })
vim.keymap.set({ "n", "x" }, "gw", "*N", { desc = "Search word under cursor" })
vim.keymap.set({ "n", "x", "o" }, "n", "'Nn'[v:searchforward]", { expr = true, desc = "Next search result" })
vim.keymap.set({ "n", "x", "o" }, "N", "'nN'[v:searchforward]", { expr = true, desc = "Prev search result" })
vim.keymap.set("v", "<", "<gv")
vim.keymap.set("v", ">", ">gv")
vim.keymap.set("n", "=", "<c-w>>")
vim.keymap.set("n", "-", "<c-w><")
vim.keymap.set("n", "+", "<c-w>+")
vim.keymap.set("n", "_", "<c-w>-")
vim.keymap.set("v", "J", "5j")
vim.keymap.set("v", "K", "5k")
vim.keymap.set("n", "<leader>ll", vim.cmd.LuaSnipEdit, { desc = "edit LuaSnip" })
vim.keymap.set("i", "<A-;>", "<End>;<ENTER>", { desc = "insert ; in this line" })

vim.keymap.set({ "o", "x" }, "ac", "<cmd>lua require('various-textobjs').multiCommentedLines()<CR>")
vim.keymap.set("n", "K", function()
	local winid = require("ufo").peekFoldedLinesUnderCursor()
	if not winid then
		vim.lsp.buf.hover()
	end
end, { desc = "hover doc" })
