local wk = require("which-key")
wk.register({ t = { name = "toggle" } }, { prefix = "<leader>" })
wk.register({ p = { name = "picker" } }, { prefix = "<leader>" })
wk.register({ b = { name = "buffer" } }, { prefix = "<leader>" })
wk.register({ s = { name = "spectre" } }, { prefix = "<leader>s" })
wk.register({ n = { name = "neorg" } }, { prefix = "<leader>" })
-- wk.register({ f = { name = "file" } }, { prefix = "<leader>" })
wk.register({ l = { name = "lsp" } }, { prefix = "<leader>" })
wk.register({ s = { name = "search" } }, { prefix = "<leader>" })
-- wk.register({ e = { name = "misc" } }, { prefix = "<leader>" })
wk.register({ g = { name = "git" } }, { prefix = "<leader>" })
wk.register({ h = { name = "help" } }, { prefix = "<leader>" })
wk.register({ r = { name = "run" } }, { prefix = "<leader>" })
wk.register({ w = { name = "window" } }, { prefix = "<leader>" })

vim.keymap.set("n", "zR", require("ufo").openAllFolds)
vim.keymap.set("n", "zM", require("ufo").closeAllFolds)
vim.keymap.set("n", "<leader>td", "<cmd>SwitchTheme dark<CR>", { desc = "toggle random dark theme" })
vim.keymap.set("n", "<leader>tl", "<cmd>SwitchTheme light<CR>", { desc = "toggle random light theme" })
vim.keymap.set("n", "<leader>hd", "<cmd>NoiceDismiss<CR>", { desc = "dismiss noice" })
vim.keymap.set("n", "<leader>ts", "<cmd>InspectTree<CR>", { desc = "open treesitter tree" })
vim.keymap.set("n", "<A-j>", ":m+1<CR>")
vim.keymap.set("n", "<A-k>", ":m-2<CR>")
vim.keymap.set("i", "<A-j>", "<esc>:m+1<CR>")
vim.keymap.set("i", "<A-k>", "<esc>:m-2<CR>")
vim.keymap.set("v", "<A-j>", ":m '>+1<CR>gv")
vim.keymap.set("v", "<A-k>", ":m '<-2<CR>gv")
vim.keymap.set("n", "<esc>", "<esc><cmd>noh<cr>")
vim.keymap.set("n", "<c-q>", "<cmd>q<CR>")
-- vim.keymap.set("n", "<leader>a", "ggVG", { desc = "select all content" })
vim.keymap.set("n", "<leader>q", vim.cmd.q, { desc = "quit" })
vim.keymap.set("n", "<c-s>", vim.cmd.w, { desc = "write" })
vim.keymap.set("i", "<c-s>", "<esc>:w<CR>", { desc = "write" })
vim.keymap.set("n", "<leader>hl", vim.cmd.Lazy, { desc = "open-lazy" })
vim.keymap.set("n", "<leader>.", ":so%<CR>")
-- vim.keymap.set("n", "<C-j>", "<c-w>j", { silent = true })
-- vim.keymap.set("n", "<C-k>", "<c-w>k", { silent = true })
-- vim.keymap.set("n", "<C-h>", "<c-w>h", { silent = true })
-- vim.keymap.set("n", "<C-l>", "<c-w>l", { silent = true })
vim.keymap.set({ "n", "x" }, "gw", "*N", { desc = "Search word under cursor" })
vim.keymap.set({ "n", "x", "o" }, "n", "'Nn'[v:searchforward]", { expr = true, desc = "Next search result" })
vim.keymap.set({ "n", "x", "o" }, "N", "'nN'[v:searchforward]", { expr = true, desc = "Prev search result" })
vim.keymap.set("v", "<", "<gv")
vim.keymap.set("v", ">", ">gv")
vim.keymap.set("v", "J", "5j")
vim.keymap.set("v", "K", "5k")
vim.keymap.set("n", "<leader>ll", vim.cmd.LuaSnipEdit, { desc = "edit LuaSnip" })
vim.keymap.set("i", "<A-;>", "<End>;<ENTER>", { desc = "insert ; in this line" })
vim.keymap.set("n", "<leader>ws", "<c-w>s", { desc = "split window" })
vim.keymap.set("n", "<leader>wv", "<c-w>v", { desc = "vertical split window" })
vim.keymap.set("n", "<leader>wh", "<c-w>h", { desc = "move to window left" })
vim.keymap.set("n", "<leader>wj", "<c-w>j", { desc = "move to window below" })
vim.keymap.set("n", "<leader>wk", "<c-w>k", { desc = "move to window up" })
vim.keymap.set("n", "<leader>wl", "<c-w>l", { desc = "move to window right" })
vim.keymap.set("n", "=", "<c-w>>")
vim.keymap.set("n", "-", "<c-w><")
vim.keymap.set("n", "+", "<c-w>+")
vim.keymap.set("n", "_", "<c-w>-")

-- vim.keymap.set({ "o", "x" }, "ac", "<cmd>lua require('various-textobjs').multiCommentedLines()<CR>")
vim.keymap.set("n", "K", function()
	local winid = require("ufo").peekFoldedLinesUnderCursor()
	if not winid then
		if next(vim.lsp.get_clients({ bufnr = 0 })) then
			vim.lsp.buf.hover()
		else
			local word = vim.fn.expand("<cword>")
			vim.cmd("Man " .. word)
		end
	end
end, { desc = "magic K" })
