local function config()
	vim.cmd("hi TreesitterContext guibg=#210102")
	require("orgmode").setup_ts_grammar()
	require("nvim-treesitter.configs").setup({
		ensure_installed = {
			"astro",
			"c",
			"lua",
			"vim",
			"fish",
			"prisma",
			"vimdoc",
			"query",
			"rust",
			"cpp",
			"fennel",
			"nix",
			"python",
			"bash",
			"typescript",
			"tsx",
			"proto",
			"html",
			"javascript",
			"java",
			"just",
			"json",
			"norg",
			"org",
			"cmake",
			"dart",
			"css",
			"diff",
			"dockerfile",
			"go",
			"gomod",
			"gitcommit",
			"git_rebase",
			"git_config",
			"php",
			"luadoc",
			"make",
			"markdown_inline",
			-- "nu",
			"sql",
			"kdl",
			"toml",
			"yaml",
			"meson",
			"zig",
			"regex",
			"gitignore",
			"markdown",
		},
		autotag = { enable = true },
		autopairs = { enable = true },
		highlight = { enable = true, disable = { "" }, additional_vim_regex_highlighting = { "org" } },
		indent = { enable = true },
		tree_setter = { enable = true },
		incremental_selection = {
			enable = true,
			keymaps = {
				init_selection = "<CR>",
				node_incremental = "<CR>",
				node_decremental = "<BS>",
				scope_incremental = "<TAB>",
			},
		},
		auto_install = false,
		sync_install = false,
	})
end
return {
	{
		"nvim-treesitter/nvim-treesitter",
		build = ":TSUpdate",
		config = config,
		event = { "BufReadPost", "BufNewFile" },
		dependencies = {
			{ "nushell/tree-sitter-nu" },
		},
	},
	-- { "m-demare/hlargs.nvim", config = true },
	{ "echasnovski/mini.ai", config = true },
	{
		"echasnovski/mini.animate",
		opts = {
			-- cursor = { enable = false },
			-- scroll = { enable = true },
		},
	},
	{ "windwp/nvim-ts-autotag", ft = { "typescriptreact", "javascriptreact", "html" } },
	{
		"chrisgrieser/nvim-various-textobjs",
		opts = { useDefaultKeymaps = true, disabledKeymaps = { "gc" } },
		event = "VeryLazy",
	},
	{
		"lewis6991/satellite.nvim",
	},
}
